// Dependency-free static release: no server, install, or original Anil directory at runtime.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const zlib = require('node:zlib');
const root = path.resolve(__dirname, '..'), out = path.resolve(root, 'dist');
if (path.dirname(out) !== root || path.basename(out) !== 'dist') throw Error('Unsafe output path');
if (fs.existsSync(out)) {
  if (!fs.existsSync(path.join(out, '.generated-release'))) throw Error('dist is not a generated release; keep it intact.');
  fs.rmSync(out, {recursive: true});
}
fs.mkdirSync(out, {recursive: true});
fs.writeFileSync(path.join(out, '.generated-release'), 'Generated by tools/build-web.cjs\n');
const files = dir => fs.readdirSync(path.join(root, dir), {withFileTypes: true}).flatMap(e =>
  e.isDirectory() ? files(`${dir}/${e.name}`) : [`${dir}/${e.name}`]);
const assetFiles = files('assets').sort((a, b) => a.startsWith('assets/story/') - b.startsWith('assets/story/') || a.localeCompare(b));
const aliases = new Map(), hashes = new Map(), story = {};
let inputBytes = 0, duplicates = 0;
function write(name, data) {
  const dest = path.join(out, name); fs.mkdirSync(path.dirname(dest), {recursive: true}); fs.writeFileSync(dest, data);
}
for (const name of assetFiles) {
  const data = fs.readFileSync(path.join(root, name)); inputBytes += data.length;
  if (name.endsWith('.json') && name.startsWith('assets/story/')) { story[name] = JSON.parse(data); continue; }
  const hash = crypto.createHash('sha256').update(data).digest('hex');
  // Only literal story image references are aliased; retain dynamic UI paths.
  if (name.startsWith('assets/story/') && hashes.has(hash)) {
    aliases.set(name, hashes.get(hash)); duplicates++; continue;
  }
  hashes.set(hash, name); write(name, data);
}
const remap = value => {
  if (typeof value === 'string') return aliases.get(value) || value;
  if (Array.isArray(value)) return value.map(remap);
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([k,v]) => [k, remap(v)]));
  return value;
};
const packed = zlib.gzipSync(JSON.stringify(remap(story)), {level: 9}).toString('base64');
write('story-pack.js', `window.SurvivorRPG=window.SurvivorRPG||{};\n(() => {
  let ready;
  window.SurvivorRPG.storyDataReady = () => ready || (ready = (async () => {
    const bytes = Uint8Array.from(atob('${packed}'), c => c.charCodeAt(0));
    const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));
    return JSON.parse(await new Response(stream).text());
  })());
})();\n`);
for (const name of files('js')) write(name, fs.readFileSync(path.join(root, name)));
write('style.css', fs.readFileSync(path.join(root, 'style.css')));
write('index.html', fs.readFileSync(path.join(root, 'index.html'), 'utf8').replace('<script src="js/main.js">', '<script src="story-pack.js"></script>\n  <script src="js/main.js">'));
write('.nojekyll', '');
write('README.txt', 'index.html을 Chrome 또는 Edge에서 열면 바로 실행됩니다.\nGitHub Pages에는 이 폴더의 내용을 올리세요.\nassets 폴더와 JS/CSS 파일은 HTML 옆에 그대로 두세요.\n조작: 방향키/WASD 이동, 이동 중 Z 유지 달리기, 정지 후 Z 대화·출전, X 포획, Enter 메뉴.\n');
let outputBytes = 0, outputFiles = 0;
function measure(dir) { for (const e of fs.readdirSync(dir, {withFileTypes: true})) {
  const file = path.join(dir, e.name); if (e.isDirectory()) measure(file); else { outputBytes += fs.statSync(file).size; outputFiles++; }
} }
measure(out);
const report = {inputAssetMB: +(inputBytes/1048576).toFixed(2), releaseMB: +(outputBytes/1048576).toFixed(2),
  duplicateImagesRemoved: duplicates, packedStoryKB: +(Buffer.byteLength(packed)/1024).toFixed(1), files: outputFiles};
write('build-report.json', JSON.stringify(report, null, 2));
console.log(JSON.stringify(report));
